### ISSUE TITLE
Write a better README file 

### ISSUE THREAD

**Issue by eugene-sergueev** [ibrsp/dataentry-cli#9]
#### TODO:

- [ ] Add AppVeyor badge;
- [ ] Provide explanation how to get latest release;
- [ ] Provide usage examples
